env = Environment(CC = 'clang++')
env.Program('valc', Glob('valc.cpp'))
env.Append(CCFLAGS=['-lm', '-lSDL2'])
env.Append(LIBS=['SDL2'])
env.Program('sieve', Glob('sieve.c'))
print('..built sieve')
env.Program('hashing', 'hashing.cpp')
print('..built hashing')
env.Program('sdl_basep',Glob('sdl_base/*.cpp'))